language: perl
perl:
  - "5.22"
  - "5.24"
matrix:
  include:
    - perl: 5.24
sudo: false             
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
