language: perl
perl:
  - "5.10"
  - "5.22"
  - "5.24"
  - "dev"               
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1   
sudo: false             
before_install:
  - dzil listdeps --develop --missing | cpanm
  - export PERL5OPT="${PERL5OPT}${PERL5OPT:+ }"'-Iblib/lib' # work around for Travis Perl helper (auto.bash $blib)
  - if [ "$COVERAGE" == "1" ]; then
      export HARNESS_PERL_SWITCHES="${HARNESS_PERL_SWITCHES}${HARNESS_PERL_SWITCHES:+ }"'-MDevel::Cover=-ignore,^x?t/,-ignore,ConfigData,-blib,0';
    fi
  - eval $(curl https://travis-perl.github.io/init) --auto
