version: build-{build}

clone_depth: 50

environment:
  PERL_CPANM_OPT: "--notest --force --skip-satisfied"

platform:
  - x64

install:
  - "cpan App::cpanminus"
  - "cpanm -v Compiler::Lexer"
  - "perl -MCompiler::Lexer -E 'print $Compiler::Lexer::VERSION'"
  - "cpanm Dist::Zilla"
  - "dzil authordeps --missing | cpanm"
  - "dzil listdeps --author --missing | cpanm"
  - "dzil listdeps --missing | cpanm"

build_script:
  - "dzil build"

test_script:
  - "dzil test --release"
