version: build-{build}

clone_depth: 50

environment:
  PERL_CPANM_OPT: "--notest --force --skip-satisfied"

platform:
  - x64

install:
  - "cpan App::cpanminus"
  - "cpanm Dist::Zilla"
  - "dzil authordeps | cpanm"
  - "dzil listdeps --author | cpanm"
  - "dzil listdeps | cpanm"

build_script:
  - "perl -MCompiler::Lexer -E 'print $Compiler::Lexer::VERSION'"
  - "dzil build"

test_script:
  - "dzil test --release"
